// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "help@paxintrade.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cities/all": {
            "get": {
                "description": "Retrieves a paginated list of city names along with their translations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cities"
                ],
                "summary": "Get a list of cities.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Number of cities to retrieve (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of cities to skip (default: 0)",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GetCitiesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.GetCitiesMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "string"
                },
                "skip": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "controllers.GetCitiesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.City"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/controllers.GetCitiesMeta"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.City": {
            "type": "object",
            "properties": {
                "deletedAt": {
                    "type": "string"
                },
                "hex": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "translations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CityTranslation"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.CityTranslation": {
            "type": "object",
            "properties": {
                "cityId": {
                    "description": "Reference to the city ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "go.paxintrade.com/api",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Paxintrade core api",
	Description:      "services paxintrade",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
